# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
os: osx
osx_image: xcode8.1
cache:
- cocoapods
- pip
before_install:
- gem install --no-rdoc --no-ri 'cocoapods:1.1.1'
- brew install clang-format
- sudo pip install lizard
- pod install --project-directory=Example
script:
- xcodebuild -scheme "$SCHEME" -workspace "$WORKSPACE" -sdk "$SDK" -destination "$DESTINATION" build test | xcpretty
- pod lib lint --allow-warnings
- ./clang-check.sh
- lizard Pod/ -C 15 -w -i 0
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=Example/SkyKit.xcworkspace
    - SCHEME="Test Runner"
    - DESTINATION="OS=10.0,name=iPhone 6S"
    - SDK=iphonesimulator
notifications:
  slack:
    secure: "hJwBS8givGXSkqUYFmfj3G6t30Dfdm45wAvD4zutnvYdGeKmbcp1H+er7/H3Gbk4k42zXupNIHuwJXzsDtrLwOYe29NXRi5SQMeR9rH9ONHBDFq5xO6mtx1ytthKaR1P37rrCh0MALFVrWaTtPpxAb53qJmMFeM0ifa2om+PEcG3eEUCsOJnABSrPStijCy5R3mhJYmUuOGuCn9sm5nh84CY6OaYU6nbJuW83JwsIR/vPBucdfHGHfM2SmUDYm4Ktpq6BcGaUYJtfyCErKG5eeWeTrfv8NjuwM/b/odscx4lS7+n6nV245GYDTroCnQ+yC9YEHWXoh1j/XghymM/iaZL5ZapXF7bjIkWKIgedvZ7yhYTHeEQKIRnzwBUZAK/Gj4a0tb4L7++oaCw4FODsJZ+rZSciJIDKo6/BQxGSNcgnnQnKJALZ/bmWFRoa35rWErb7qo2vrGsNdySs3WWxIjohvcofnuLWHKAliCWbkZhqYSm+c38r8/S72l0V8GepBXutPkmjUV/d/7EHjaluIxnc8A/Xej5yEl4/5w3/C4EOougOsoUpWgIhn8D2GaFzuqzWFmK9CDGV7Ga+zEzSAONW3RdEn829hJHJ4n9YChMzkGC0L/XhYtWmkS/9aaTyBSrloexHAYNlTZ+0SPXVNYkG4H/0Kvg6mit+bvyzNE="
